{
 "title": "real-time-stock-pipeline",
 "time": { "from": "2025-06-12T14:42:00.000Z", "to": "2025-06-12T15:56:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "symbol",
    "label": "symbol",
    "query": "SELECT DISTINCT symbol FROM ohlcv_data ORDER BY symbol;"
   }
  ]
 },
 "panels": [
  {
   "title": "Last Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  symbol,\r\n  price\r\nFROM tick_data\r\nWHERE symbol = '$symbol'\r\nORDER BY event_time DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "1-Min Price Volatility",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  symbol,\r\n  max(price) - min(price) AS volatility\r\nFROM tick_data\r\nWHERE event_time > now() - interval '1 minute'\r\nGROUP BY symbol\r\nORDER BY volatility DESC;"
    }
   ]
  },
  {
   "title": "Price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT event_time, price FROM tick_data WHERE symbol = '${symbol}'\r\n"
    }
   ]
  },
  {
   "title": "OHLCV",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT * FROM ohlcv_data WHERE symbol = '${symbol}'\r\n"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT event_time, volume FROM tick_data WHERE symbol = '${symbol}'\r\n"
    }
   ]
  }
 ]
}